### ISSUE TITLE
TS

### ISSUE THREAD

**Issue by josssp** [VZalesinski/test-components#1]
Добрый день, не могли бы вы включить TS в свой проект и "переписать" код на TS

По готовности сообщите Анне.

**Comment by VZalesinski** [comment]
Добрый! Хорошо

вт, 6 дек. 2022 г., 09:29 Joss ***@***.***>:

**Comment by VZalesinski** [comment]
готово

> Добрый день, не могли бы вы включить TS в свой проект и "переписать" код на TS
> 
> По готовности сообщите Анне.
